service: greenstagram

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: ${self:provider.stage}
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    AZURE_CLIENT_ID: ${env:AZURE_CLIENT_ID}
    AZURE_CLIENT_SECRET: ${env:AZURE_CLIENT_SECRET}
    AZURE_TENANT_ID: ${env:AZURE_TENANT_ID}
    REDIS_URL: ${env:REDIS_URL}

functions:
  api:
    handler: backend/dist/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3001
    stage: local

package:
  exclude:
    - frontend/**
    - node_modules/**
    - .git/**
    - README.md
    - .env*
  include:
    - backend/dist/**