version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: backend-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: backend_db_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - backend-network-dev

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: backend-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - backend-network-dev

  # Backend Application (Development mode with hot reload)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend-app-dev
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/backend_db_dev?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      FRONTEND_URL: http://localhost:3000
      JWT_SECRET: dev-jwt-secret-key
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - backend-network-dev

networks:
  backend-network-dev:
    driver: bridge

volumes:
  mongodb_data_dev:
    driver: local
  redis_data_dev:
    driver: local